facet/base/urls.py
from django.urls import path

from .views import (
    dashboard,
)


app_name = 'base'
urlpatterns = [
    path('', dashboard.LandingTemplateView.as_view(), name='landing'),
    path('dashboard/', dashboard.DashboardDeterminationView.as_view(), name='dashboard'),
    path('dashboard/account-requested/', dashboard.PreAccountApprovalDashboardView.as_view(), name='dashboard_account_requested'),
]

facet/editorial/urls.py
from django.urls import path

from .views import (
    project,
    story,
    item,
    item_template,
    asset,
)

app_name = 'editorial'
urlpatterns = [
    #Project
    path('project/new/', project.ProjectCreateView.as_view(), name='project_new'),
    path('project/<pk>/', project.ProjectDetailView.as_view(), name='project_detail'),
    path('project/<pk>/update/', project.ProjectUpdateView.as_view(), name='project_update'),
    path('project/<pk>/delete/', project.ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<pk>/team/update/', project.ProjectTeamUpdateView.as_view(), name='project_team_update'),
    path('project/<pk>/stories/', project.ProjectStoryView.as_view(), name='project_stories'),
    path('project/<pk>/assets/', project.ProjectAssetView.as_view(), name='project_assets'),
    path('project/<pk>/tasks/', project.ProjectTaskView.as_view(), name='project_tasks'),
    path('project/<pk>/notes/', project.ProjectNoteView.as_view(), name='project_notes'),
    # path('/project/<pk>/note/(?P<note>\d+)/content$', notes.NoteContent.as_view(), name='note_content'),
    path('project/<pk>/calendar/', project.ProjectScheduleView.as_view(), name='project_schedule'),
    # Project lists
    path('project/list/', project.ProjectListRedirectView.as_view(), name='project_list'),
    path('<pk>/project/list/', project.StaffJournalistProjectListView.as_view(), name='staff_project_list'),
    path('<pk>/project/list/', project.UnaffiliatedStaffJournalistProjectListView.as_view(), name='unaffiliated_project_list'),
    path('<pk>/project/list/', project.FreelanceJournalistProjectListView.as_view(), name='freelance_project_list'),
    path('<pk>/project/list/', project.NewsOrganizationProjectListView.as_view(), name='newsorganization_project_list'),
    path('<pk>/project/list/', project.NewsOrganizationNetworkProjectListView.as_view(), name='newsnetwork_project_list'),
    # Story
    path('story/new/', story.StoryCreateView.as_view(), name='story_new'),
    path('story/<pk>/', story.StoryDetailView.as_view(), name='story_detail'),
    path('story/<pk>/update/', story.StoryUpdateView.as_view(), name='story_update'),
    path('story/<pk>/delete/', story.StoryDeleteView.as_view(), name='story_delete'),
    path('story/<pk>/team/update/', story.StoryTeamUpdateView.as_view(), name='story_team_update'),
    path('story/<pk>/items/', story.StoryItemView.as_view(), name='story_items'),
    path('story/<pk>/assets/', story.StoryAssetView.as_view(), name='story_assets'),
    path('story/<pk>/tasks/', story.StoryTaskView.as_view(), name='story_tasks'),
    path('story/<pk>/notes/', story.StoryNoteView.as_view(), name='story_notes'),
    # path('/story/<pk>/note/(?P<note>\d+)/content$', notes.NoteContent.as_view(), name='note_content'),
    path('story/<pk>/calendar/', story.StoryScheduleView.as_view(), name='story_schedule'),
    # Story lists
    path('story/list/', story.StoryListRedirectView.as_view(), name='story_list'),
    path('<pk>/story/list/', story.StaffJournalistStoryListView.as_view(), name='staff_story_list'),
    path('<pk>/story/list/', story.UnaffiliatedStaffJournalistStoryListView.as_view(), name='unaffiliated_story_list'),
    path('<pk>/story/list/', story.FreelanceJournalistStoryListView.as_view(), name='freelance_story_list'),
    path('<pk>/story/list/', story.NewsOrganizationStoryListView.as_view(), name='newsorganization_story_list'),
    path('<pk>/story/list/', story.NewsOrganizationNetworkStoryListView.as_view(), name='newsnetwork_story_list'),
    #Item
    path('story/<story>/item/add/', item.ItemPreCreateView.as_view(), name="item_precreate"),
    path('story/<story>/item/add/<pk>/', item.ItemCreateView.as_view(), name="item_add"),
    path('story/<story>/item/<pk>/update/', item.ItemUpdateView.as_view(), name="item_update"),
    path('story/<story>/item/<pk>/delete/', item.ItemDeleteView.as_view(), name="item_delete"),
    # Item templates
    path('item/templates/', item_template.ItemTemplateListView.as_view(), name="item_template_list"),
    path('item/templates/create/', item_template.ItemTemplateCreateView.as_view(), name="item_template_create"),
    path('item/templates/<pk>/', item_template.ItemTemplateDetailView.as_view(), name="item_template_detail"),
    path('item/templates/<pk>/update/', item_template.ItemTemplateUpdateView.as_view(), name="item_template_update"),
    path('item/templates/<pk>/delete/', item_template.ItemTemplateDeleteView.as_view(), name="item_template_delete"),
    # Asset
    path('library', asset.AssetLibraryTemplateView.as_view(), name='asset_library'),
    # # Image Asset
    path('images/', asset.ImageAssetLibraryTemplateView.as_view(), name='image_asset_list'),
    path('image/new/', asset.ImageAssetCreateView.as_view(), name='upload_image'),
    path('image/<pk>/', asset.ImageAssetUpdateView.as_view(), name='image_asset_detail'),
    path('image/<pk>/delete/', asset.ImageAssetDeleteView.as_view(), name='image_asset_delete'),
    path('image/<pk>/item/<item>/remove/', asset.ImageAssetDisassociateView.as_view(), name='image_asset_remove'),
    path('story/<story>/item/<item>/images/add/', asset.LibraryImageAssociateView.as_view(), name='library_image_add'),
    # # Document Asset
    path('documents/', asset.DocumentAssetLibraryTemplateView.as_view(), name='document_asset_list'),
    path('document/new/', asset.DocumentAssetCreateView.as_view(), name='upload_document'),
    path('document/<pk>/', asset.DocumentAssetUpdateView.as_view(), name='document_asset_detail'),
    path('document/<pk>/delete/', asset.DocumentAssetDeleteView.as_view(), name='document_asset_delete'),
    path('document/<pk>/item/<item>/remove/', asset.DocumentAssetDisassociateView.as_view(), name='document_asset_remove'),
    path('story/<story>/item/<item>/documents/add/', asset.LibraryDocumentAssociateView.as_view(), name='library_document_add'),
    # # Audio Asset
    path('audio/', asset.AudioAssetLibraryTemplateView.as_view(), name='audio_asset_list'),
    path('audio/new/', asset.AudioAssetCreateView.as_view(), name='upload_audio'),
    path('audio/<pk>/', asset.AudioAssetUpdateView.as_view(), name='audio_asset_detail'),
    path('audio/<pk>/delete/', asset.AudioAssetDeleteView.as_view(), name='audio_asset_delete'),
    path('audio/<pk>/item/<item>/remove/', asset.AudioAssetDisassociateView.as_view(), name='audio_asset_remove'),
    path('story/<story>/item/<item>/audio/add/', asset.LibraryAudioAssociateView.as_view(), name='library_audio_add'),
    # # Video Asset
    path('video/', asset.VideoAssetLibraryTemplateView.as_view(), name='video_asset_list'),
    path('video/new/', asset.VideoAssetCreateView.as_view(), name='upload_video'),
    path('video/<pk>/', asset.VideoAssetUpdateView.as_view(), name='video_asset_detail'),
    path('video/<pk>/delete/', asset.VideoAssetDeleteView.as_view(), name='video_asset_delete'),
    path('video/<pk>/item/<item>/remove/', asset.VideoAssetDisassociateView.as_view(), name='video_asset_remove'),
    path('story/<story>/item/<item>/video/add/', asset.LibraryVideoAssociateView.as_view(), name='library_video_add'),
]

facet/editorial/models/item.py
from django.contrib.postgres.fields import ArrayField
# from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
# from internal_history.models import HistoricalRecords

from base.models import Participant, EntityOwner, Anchor
from entity.models import NewsOrganization
from .story import Story
from .item_template import ItemTemplate
from .content_license import ContentLicense
from .tag import Tag


class Item(models.Model):
    """A version of a story.

    An item must belong to a story and can only belong to one story. An item is a version
    of the story.

    Items can have two owners, the participant that made them and the organization that
    participant belongs to, if any.

    Ex. A story about wildfires could have:
    - a web story item that is a text article with photos and video
    - a host-wrap item that is the radio script of a story about the fire
    - a video item that is a video segment about the fire for distribution via social media.
    - an item that is a version of the story in a different language.
    """

    # populated automatically
    anchor_profile = models.OneToOneField(Anchor, null=True, on_delete=models.SET_NULL)

    participant_owner = models.OneToOneField(
        Participant,
        help_text = 'Participant who created/owns this.',
        null = True,
        on_delete = models.SET_NULL,
    )

    entity_owner = models.OneToOneField(
        EntityOwner,
        help_text = 'Entity that owns this.',
        null = True,
        on_delete = models.SET_NULL,
    )

    template = models.ForeignKey(
        ItemTemplate,
        on_delete = models.SET_DEFAULT,
        default=1,
    )

    story = models.ForeignKey(
        Story,
        on_delete = models.CASCADE,
        help_text ='Parent story of this item.',
    )

    original = models.BooleanField(
        default=True,
        help_text='If original to participant/entity, true. If picked up, false.',
        # If item is not original, set to false and use ItemPickupDetail for additional info.
    )

    creation_date = models.DateTimeField(
        auto_now_add=True,
        help_text='Date time item was created.',
    )

    # populated by participant
    name = models.TextField(
        # displayed on form as label
        help_text='Internal name for item.'
    )

    headline = models.TextField(
        help_text='Headline of the item',
    )

    description = models.TextField(
        help_text='Description of the item.',
        blank=True,
    )

    editor = models.ManyToManyField(
        Participant,
        related_name='item_editor',
        help_text='The full participant name(s) to be listed as the editor(s) for the item.',
        blank=True,
    )

    credit = models.ManyToManyField(
        Participant,
        related_name='item_credit',
        help_text='The full participant name(s) to be listed as the credit for the item.',
        blank=True,
    )

    team = models.ManyToManyField(
        Participant,
        related_name='item_team_member',
        help_text='Contributing participant.',
        blank=True,
    )

    content = models.TextField(
        help_text='Content of the item.',
        blank=True,
    )

    # Choices for item status.
    DRAFT = 'Draft'
    PITCH = 'Pitch'
    IN_PROGRESS = 'In Progress'
    EDIT = 'Edit'
    REVISION = 'Revision'
    NEEDS_REVIEW = 'Needs Review'
    READY = 'Ready'
    ITEM_STATUS_CHOICES = (
        (DRAFT, 'Draft'),
        (PITCH, 'Pitch'),
        (IN_PROGRESS, 'In Progress'),
        (EDIT, 'Edit'),
        (REVISION, 'Revision'),
        (NEEDS_REVIEW, 'Needs Review'),
        (READY, 'Ready'),
    )

    status = models.CharField(
        max_length=25,
        choices=ITEM_STATUS_CHOICES,
        help_text='Item status choice.',
        default='DRAFT',
    )

    due_edit = models.DateTimeField(
        help_text='Due for edit.',
        blank=True,
        null=True,
    )

    run_date = models.DateTimeField(
        help_text='Planned run date.',
        blank=True,
        null=True,
    )

    content_license = models.ForeignKey(
        ContentLicense,
        blank=True,
        null=True,
        on_delete = models.SET_NULL,
    )

    tags = models.ManyToManyField(Tag, blank=True)

    # assets
    image_assets = models.ManyToManyField('ImageAsset', blank=True)
    document_assets = models.ManyToManyField('DocumentAsset', blank=True)
    audio_assets = models.ManyToManyField('AudioAsset', blank=True)
    video_assets = models.ManyToManyField('VideoAsset', blank=True)

    # history
    # edit_history = HistoricalRecords()

    # ------------------------#
    # optional fields
    # ------------------------#

    #Now handled on update model
    # update_note  = models.TextField(
    #     help_text='Text commenting regarding any updates or corrections made to the item.',
    #     blank=True,
    # )

    excerpt = models.TextField(
        help_text='Excerpt from the item.',
        blank=True,
    )

    dateline = models.CharField(
        max_length=150,
        help_text='Where and when the item was created.',
        blank=True,
    )

    share_note = models.TextField(
        help_text='Information for organizations making a copy of the item.',
        blank=True,
    )

    topic_code = models.CharField(
        max_length=75,
        help_text='Unique code as needed to designate topic or coverage.',
        blank=True,
    )

    internal_code = models.CharField(
        max_length=75,
        help_text='Unique code as needed for ingest sytems or internal use. Use as needed.',
        blank=True,
    )

    length = models.CharField(
        max_length=75,
        help_text='Length of item for audio or video.',
        blank=True,
    )

    wordcount = models.CharField(
        max_length=75,
        help_text='Wordcount for text-based items.',
        blank=True,
    )

    related_links = models.TextField(
        help_text='Relevant links that can be included with the item.',
        blank=True,
    )

    github_link = models.URLField(
        max_length=300,
        help_text='Link to code for any custom feature.',
        blank=True,
    )

    # removed as will be handled in RollCall
    # sources = models.TextField(
    #     help_text='List of sources in the item.',
    #     blank=True,
    # )

    edit_note = models.TextField(
        help_text='Information regarding allowable extent of editing and suggestions for specific kinds of edits.',
        blank=True,
    )

    pronounciations = models.TextField(
        help_text='Information about pronouncing names or potentially difficult words.',
        blank=True,
    )

    #moving to separate model, perhaps capital
    # sponsors = models.TextField(
    #     help_text='Sponsors or underwriters if need to indicate any.',
    #     blank=True,
    # )

    # ------------------------#
    #   web specific fields
    # ------------------------#

    # also relevant for print
    pull_quotes = models.TextField(
        help_text='List of quotes and attributions to be used as pull quotes.',
        blank=True,
    )

    embeds = models.TextField(
        help_text='The necessary information to embed something like a Tweet, FB post, map or video.',
        blank=True,
    )

    # push to CMS history
    # pushed_to_wp = models.BooleanField(
    #     default=False,
    #     help_text='Whether the item has been pushed to the organization WordPress site.',
    # )

    # ------------------------#
    # print specific fields
    # ------------------------#

    sidebar_content = models.TextField(
        help_text='Content separate from body text meant for sidebar or inset presentation.',
        blank=True,
    )

    # ------------------------#
    # audio specific fields
    # ------------------------#

    # relevant for video
    # producer = models.ForeignKey(
    #     Participant,
    #     related_name='itemproducer',
    #     blank=True,
    #     null=True,
    # )

    # ------------------------#
    # tv and video specific
    # ------------------------#

    series_title = models.TextField(
        help_text='Title of the video series.',
        blank=True,
    )

    episode_number = models.CharField(
        max_length=75,
        help_text='If the video is part of a series, the episode number.',
        blank=True,
    )

    usage_rights = models.TextField(
        help_text='Information regarding the usage of the video if shared.',
        blank=True,
    )

    tape_datetime = models.DateTimeField(
        help_text='Tape date.',
        blank=True,
        null=True,
    )

    locations = models.TextField(
        help_text='Shoot locations.',
        blank=True,
    )

    # ------------------------#
    # participant defined fields
    # ------------------------#

    custom_one = models.TextField(
        help_text='Participant-defined field.',
        blank=True,
    )

    custom_two = models.TextField(
        help_text='Participant-defined field.',
        blank=True,
    )

    custom_three = models.TextField(
        help_text='Participant-defined field.',
        blank=True,
    )

    custom_four = models.TextField(
        help_text='Participant-defined field.',
        blank=True,
    )

    custom_five = models.TextField(
        help_text='Participant-defined field.',
        blank=True,
    )

    class Meta:
        verbose_name='Item'
        verbose_name_plural='Items'
        # ordering = ['name']

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('item_edit', kwargs={'pk': self.id, 'story': self.story_id})

    @property
    def search_title(self):
        return self.name

    @property
    def type(self):
        return "Item"

    # def copy(self):
    #     """ Create a copy of an item for a partner organization in a network."""
    #

facet/editorial/templates/item/_item_audioasset_modal.html
<!-- Audio Asset Modal -->

<div class="modal fade" id="AudioAssetModal" tabindex="-1" role="dialog" aria-labelledby="AudioAssetModal">
  <div class="modal-dialog modal-lg" role="audio">
    <div class="modal-content">
      <div class="bs-nav-tabs nav-tabs-default">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <ul class="nav nav-tabs nav-animated-border-from-left">
            <li class="nav-item"> <a ng-href="" class="nav-link active" data-toggle="tab" data-target="#uploadaudio">Upload a Audio</a></li>
            <li class="nav-item"> <a id="selectaudiolibrary" ng-href="" class="nav-link" data-toggle="tab" data-target="#audiolibrary">Select From Audio Library</a></li>
          </ul>
        </div>
        {% with view.facet_audio_assets as audio_assets %}
        <div class="modal-body" id="audiomodalbody">
          <div class="tab-content">
            <!-- UPLOAD PANEL -->
            <div role="tabpanel" class="tab-pane active" id="uploadaudio">
              <div class="uploadpanel" data-toggle="slimScroll" style="height:500px" data-color="#5D9CEC" data-allow-page-scroll="false">
              <form action="{% url 'editorial:upload_audio' %}" method="POST" class="post-form" enctype="multipart/form-data">
              {% csrf_token %}

                <!-- Left Col -->
                <div class="col-md-6">

                  <fieldset class="form-group m-b-10">
                    <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ audio_assets.uploadform.audio.label_tag }}</label>
                    {{ audio_assets.uploadform.audio }}
                    {% if audio_assets.uploadform.audio.errors %}
                      <small class="text-muted">{{ audio_assets.uploadform.audio.errors }}</small>
                    {% endif %}
                  </fieldset>

                  <fieldset class="form-group m-b-10">
                    <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ audio_assets.uploadform.link.label_tag }}</label>
                    {{ audio_assets.uploadform.link }}
                    {% if audio_assets.uploadform.link.errors %}
                      <small class="text-muted">{{ audio_assets.uploadform.link.errors }}</small>
                    {% endif %}
                  </fieldset>

                  <fieldset class="form-group m-b-10">
                    <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ audio_assets.uploadform.title.label_tag }}</label>
                    {{ audio_assets.uploadform.title }}
                    {% if audio_assets.uploadform.title.errors %}
                      <small class="text-muted">{{ audio_assets.uploadform.title.errors }}</small>
                    {% endif %}
                  </fieldset>

                  <fieldset class="form-group m-b-10">
                    <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ audio_assets.uploadform.asset_type.label_tag }}</label>
                    {{ audio_assets.uploadform.asset_type }}
                    {% if audio_assets.uploadform.asset_type.errors %}
                      <small class="text-muted">{{ audio_assets.uploadform.asset_type.errors }}</small>
                    {% endif %}
                  </fieldset>

                  <fieldset class="form-group m-b-10">
                    <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ audio_assets.uploadform.keywords.label_tag }}</label>
                    {{ audio_assets.uploadform.keywords }}
                    {% if audio_assets.uploadform.keywords.errors %}
                      <small class="text-muted">{{ audio_assets.uploadform.keywords.errors }}</small>
                    {% endif %}
                  </fieldset>

                </div>
                <!-- End Left Col -->
                <!-- Right Col -->
                <div class="col-md-6">

                  <fieldset class="form-group m-b-10">
                    <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ audio_assets.uploadform.description.label_tag }}</label>
                    {{ audio_assets.uploadform.description }}
                    {% if audio_assets.uploadform.description.errors %}
                      <small class="text-muted">{{ audio_assets.uploadform.description.errors }}</small>
                    {% endif %}
                  </fieldset>

                  <fieldset class="form-group m-b-10">
                    <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ audio_assets.uploadform.attribution.label_tag }}</label>
                    {{ audio_assets.uploadform.attribution }}
                    {% if audio_assets.uploadform.attribution.errors %}
                      <small class="text-muted">{{ audio_assets.uploadform.attribution.errors }}</small>
                    {% endif %}
                  </fieldset>

                </div>
                <!-- End Right Col -->
                <!-- ===================================== -->
                <!-- ===================================== -->
                <div class="hidden-image-inputs">
                    <input type="hidden" name="facet" value="{{ facet.pk }}" />
                </div>
                <!-- ===================================== -->
                <!-- ===================================== -->
                <div>
                    <button type="submit" class="btn btn-primary m-l-20">Save Audio</button>
                </div>

              </form>
              </div>
            </div>
            <!-- END UPLOAD PANEL -->

            <!-- LIBRARY PANEL -->
            <div role="tabpanel" class="tab-pane" id="audiolibrary">
              <!-- Loading _libraryaudio.html -->
            </div>
            <!-- END LIBRARY PANEL -->
          </div>
        </div>
        {% endwith %}
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
</div>

{% if facet %}
<script>
  $("#selectaudiolibrary").on("show.bs.tab", function (e) {
      $("#audiolibrary").load("{% url 'editorial:library_audio_add' facet=facet.id story=facet.story.id %}")
  })
</script>
{% endif %}

facet/editorial/templates/item/_item_documentasset_modal.html
<!-- Document Asset Modal -->

<div class="modal fade" id="DocumentAssetModal" tabindex="-1" role="dialog" aria-labelledby="DocumentAssetModal">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="bs-nav-tabs nav-tabs-default">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <ul class="nav nav-tabs nav-animated-border-from-left">
            <li class="nav-item"> <a ng-href="" class="nav-link active" data-toggle="tab" data-target="#uploaddocument">Upload a Document</a></li>
            <li class="nav-item"> <a id="selectdocumentlibrary" ng-href="" class="nav-link" data-toggle="tab" data-target="#documentlibrary">Select From Document Library</a></li>
          </ul>
        </div>
        {% with view.facet_document_assets as document_assets %}
        <div class="modal-body" id="documentmodalbody">
          <div class="tab-content">
            <!-- UPLOAD PANEL -->
            <div role="tabpanel" class="tab-pane active" id="uploaddocument">
              <div class="uploadpanel" data-toggle="slimScroll" style="height:500px" data-color="#5D9CEC" data-allow-page-scroll="false">
              <form action="{% url 'editorial:upload_document' %}" method="POST" class="post-form" enctype="multipart/form-data">
              {% csrf_token %}
              <!-- Left Col -->
              <div class="col-md-6">

                <fieldset class="form-group m-b-10">
                  <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ document_assets.uploadform.document.label_tag }}</label>
                  {{ document_assets.uploadform.document }}
                  {% if document_assets.uploadform.document.errors %}
                    <small class="text-muted">{{ document_assets.uploadform.document.errors }}</small>
                  {% endif %}
                </fieldset>

                <fieldset class="form-group m-b-10">
                  <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ document_assets.uploadform.title.label_tag }}</label>
                  {{ document_assets.uploadform.title }}
                  {% if document_assets.uploadform.title.errors %}
                    <small class="text-muted">{{ document_assets.uploadform.title.errors }}</small>
                  {% endif %}
                </fieldset>

                <fieldset class="form-group m-b-10">
                  <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ document_assets.uploadform.asset_type.label_tag }}</label>
                  {{ document_assets.uploadform.asset_type }}
                  {% if document_assets.uploadform.asset_type.errors %}
                    <small class="text-muted">{{ document_assets.uploadform.asset_type.errors }}</small>
                  {% endif %}
                </fieldset>

                <fieldset class="form-group m-b-10">
                  <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ document_assets.uploadform.keywords.label_tag }}</label>
                  {{ document_assets.uploadform.keywords }}
                  {% if document_assets.uploadform.keywords.errors %}
                    <small class="text-muted">{{ document_assets.uploadform.keywords.errors }}</small>
                  {% endif %}
                </fieldset>

              </div>
              <!-- End Left Col -->
              <!-- Right Col -->
              <div class="col-md-6">

                <fieldset class="form-group m-b-10">
                  <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ document_assets.uploadform.description.label_tag }}</label>
                  {{ document_assets.uploadform.description }}
                  {% if document_assets.uploadform.description.errors %}
                    <small class="text-muted">{{ document_assets.uploadform.description.errors }}</small>
                  {% endif %}
                </fieldset>

                <fieldset class="form-group m-b-10">
                  <label class="f-s-14 f-s-400 spread-01 subtle slim-margin">{{ document_assets.uploadform.attribution.label_tag }}</label>
                  {{ document_assets.uploadform.attribution }}
                  {% if document_assets.uploadform.attribution.errors %}
                    <small class="text-muted">{{ document_assets.uploadform.attribution.errors }}</small>
                  {% endif %}
                </fieldset>

              </div>
              <!-- End Right Col -->
              <!-- ===================================== -->
              <!-- ===================================== -->
              <div class="hidden-document-inputs">
                  <input type="hidden" name="facet" value="{{ facet.pk }}" />
              </div>
              <!-- ===================================== -->
              <!-- ===================================== -->
              <div>
                <button type="submit" class="btn btn-primary m-l-20">Save Document</button>
              </div>
              </form>
              </div>
            </div>
            <!-- END UPLOAD PANEL -->

            <!-- LIBRARY PANEL -->
            <div role="tabpanel" class="tab-pane" id="documentlibrary">
              <!-- Loading _librarydocument.html -->
            </div>
            <!-- END LIBRARY PANEL -->
          </div>
        </div>
        {% endwith %}
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
</div>

{% if facet %}
<script>
  $("#selectdocumentlibrary").on("show.bs.tab", function (e) {
      $("#documentlibrary").load("{% url 'editorial:library_document_add' facet=facet.id story=facet.story.id %}")
  })
</script>
{% endif %}

facet/editorial/templates/item/item_delete.html
{% extends 'base_editorial.html' %}
{% load i18n %}

{% load static %}

<!-------------------------------------------->
<!--            Main Section                -->
<!-------------------------------------------->

{% block content %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="login-page text-center animated fadeIn delay-1000">
          <h6 class="cover-heading center">{{ item }} Delete</h6>
          <form method="POST" class="post-form">
            {% csrf_token %}
            <input type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}